# Generated by Django 5.2.3 on 2025-06-21 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_data', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField()),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Fuel', 'Fuel'), ('Travel', 'Travel'), ('Bills', 'Bills'), ('Shopping', 'Shopping'), ('HealthCare', 'HealthCare'), ('Miscellanious', 'Miscellanious')], default='Food', max_length=100)),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('CASH', 'CASH')], default='CASH', max_length=200)),
                ('priority', models.CharField(choices=[('NEED', 'NEED'), ('WANT', 'WANT')], default='NEED', max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
